NPM ?= npm

.PHONY: deps build typecheck dev package clean

deps:
	$(NPM) install

build:
	$(NPM) run build

typecheck:
	$(NPM) run typecheck

dev:
	$(NPM) run dev

package:
	$(NPM) run package

clean:
	$(NPM) run clean
